#!/bin/bash
# This file is a part of quicksave project.
# Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.

cd $(dirname $0)

BEANS_REPOSITORY=${1:-https://github.com/adiog/io_quicksave_beans}
shift 1
SPECIFIC_BEANS_ONLY=$*
echo SPECIFIC_BEANS_ONLY=$SPECIFIC_BEANS_ONLY

git clone $BEANS_REPOSITORY beans-tmp
BEANS_DIR=`pwd`/beans-tmp

OUTPUT_DIR=../src/quicksave_pybeans/generated/
mkdir -p $OUTPUT_DIR

if [[ -z "$SPECIFIC_BEANS_ONLY" ]];
then
    BEANS=$(ls -1 $BEANS_DIR/*.json)
else
    for BEAN in $SPECIFIC_BEANS_ONLY;
    do
        BEANS="$BEANS $BEAN.json"
    done
fi

for BEAN in $BEANS;
do
    BEANS_UNORDERED="$BEANS_UNORDERED $(basename $BEAN)"
done

BEANS=`python3 do_sort.py $BEANS_DIR $BEANS_UNORDERED`

(
echo '# This file is an AUTOGENERATED part of beans project.'
echo '# Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.'
echo ''
echo 'import quicksave_pybeans.pybeans'
echo ''
) > ${OUTPUT_DIR}/QsBeans.py

for bean_file in $BEANS;
do
    BEAN=$(basename $bean_file);
    echo "Generating $BEAN ..."
    python3 do_generate.py $BEANS_DIR ${BEAN} >> $OUTPUT_DIR/QsBeans.py
    echo "... generating $BEAN [DONE]"
done

rm -fr $BEANS_DIR